//
// Created by huang on 8/23/18.
//

#ifndef PROJECT_ZMQ_DEFINES_H
#define PROJECT_ZMQ_DEFINES_H

#define SID_ROS_SIMULATION_CARRIER_TO_MCU			7819	//PUB-SUB
#define SID_ROS_SIMULATION_CARRIER_TO_LIDAR		7820	//PUB-SUB
#define SID_ROS_SIMULATION_MCU_TO_CARRIER     7821    //PUB-SUB
#define SID_ROS_SIMULATION_LIDAR_TO_CARRIER		7822	//PUB-SUB

#endif //PROJECT_ZMQ_DEFINES_H
